version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: www-data
        uid: 1000
    image: bagisto-app
    container_name: bagisto-app
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    platform: linux/amd64
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bagisto
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: bagisto-mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bagisto

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bagisto-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql-data:
